### ISSUE TITLE
Неверный описание поля для ввода

### ISSUE THREAD

**Issue by Arina-Ib** [CsharpMaster37/BookMarket#4]
1) В главном окне приложение добавляем книгу(-и), нажимаем на значок покупки книги, при заполнении формы, будет необходимо ввести ФИО
![photo_5438152329246397678_x](https://github.com/CsharpMaster37/BookMarket/assets/144983087/63499edd-6fb0-42a8-8c9c-cbdd0b23012e)
2) Допускается ввод цифр
![photo_5438152329246397687_x](https://github.com/CsharpMaster37/BookMarket/assets/144983087/0185f6ce-2809-41d9-8024-af020557b275)
3) Ожидаемое поведение: переименовать поле, так как подразумевается ввод не ФИО, а имени пользователя (где допускаются цифры)

**Comment by aizek3345** [comment]
Исправлено
