### ISSUE TITLE
Неверное отображение имени пользователя в разделе "История продаж"

### ISSUE THREAD

**Issue by Arina-Ib** [CsharpMaster37/BookMarket#5]
1) В главном окне приложение добавляем книгу(-и), нажимаем на значок покупки книги, при заполнении формы, будет необходимо ввести ФИО

![photo_5438152329246397678_x](https://github.com/CsharpMaster37/BookMarket/assets/144983087/1fc473a8-0321-4a03-ba41-226edcd79267)

2) Вводим имя пользователя "ПервоеСловоВтороеСловоТретьеСловоЧетвертоеСлово", остальные необходимые данные, покупаем книгу

![photo_5438152329246397674_x](https://github.com/CsharpMaster37/BookMarket/assets/144983087/4192e8dd-5c63-4210-abd5-c785c413b565)

переходим в раздел "История продаж" в верхнем меню и видим, что имя отображается с середины 

![photo_5438152329246397675_m](https://github.com/CsharpMaster37/BookMarket/assets/144983087/5c041ff5-1b4d-49de-b751-37e332819f28)

3) Ожидаемое поведение: отображение имени целиком посредством ограничения длины для имени пользователя

**Comment by aizek3345** [comment]
Исправлено
