### ISSUE TITLE
Неверный формат ввода данных при добавлении книги

### ISSUE THREAD

**Issue by Arina-Ib** [CsharpMaster37/BookMarket#6]
1) В стартовом окне приложения нажимаем кнопку "Добавить книгу" и вводим во все поля единицы и добавляем такую книгу
![photo_5438152329246397736_x](https://github.com/CsharpMaster37/BookMarket/assets/144983087/69c056a9-9697-4582-9975-931624e8bcab)
2) Кинга успешно добавилась
![photo_5438152329246397738_y](https://github.com/CsharpMaster37/BookMarket/assets/144983087/6b43084b-0eff-488d-b88c-c04bf4c89628)
![photo_5438152329246397647_x (1)](https://github.com/CsharpMaster37/BookMarket/assets/144983087/96b20760-90ca-42e2-9631-d524af347ede)
3) Ожидаемое поведение: отсутствие возможности заполнять поля Категория и Тематика цифрами

**Comment by aizek3345** [comment]
Исправлено
