### ISSUE TITLE
Отсутствие сообщения об ошибке при генерации отрицательного числа книг

### ISSUE THREAD

**Issue by Arina-Ib** [CsharpMaster37/BookMarket#7]
1) В стартовом окне приложения нажимаем кнопку "Сгенерировать" и вводим в поле "кол-во" отрицательное значение 
![photo_5438152329246397648_m](https://github.com/CsharpMaster37/BookMarket/assets/144983087/3cb98982-46c0-43aa-b1b8-8a18fbc371bd)
2) После нажатия на кнопку "ок" ничего не происходит: книги не создаются, но и сообщение об ошибке не выводится 
3) Ожидаемое поведение: вывод на экран сообщения об ошибке

**Comment by aizek3345** [comment]
Исправлено
